apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: node_user
  DB_PASSWORD: supersecurepassword
  DB_NAME: node_app_db
  POSTGRES_USER: node_user
  POSTGRES_PASSWORD: supersecurepassword
  POSTGRES_DB: node_app_db

